version: "3.8"

services:
  fastapi:
    build:
      context: .        # 현재 디렉토리 기준
      dockerfile: Dockerfile
    container_name: momo_fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - DB_URL=postgresql+psycopg2://user:p1234@postgres:5432/momo
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # .env에 저장된 키를 자동 주입
    volumes:
      - .:/app

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: momo_celery
    restart: always
    depends_on:
      - redis
      - postgres
    command: celery -A app.celery_worker.celery_app worker --loglevel=info
    environment:
      - DB_URL=postgresql+psycopg2://user:p1234@postgres:5432/momo
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app

  postgres:
    image: ankane/pgvector:latest
    container_name: momo_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: p1234
      POSTGRES_DB: momo
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: momo_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
