# AI/docker-compose.yml

services:
  redis:
    image: "redis:alpine"
    container_name: momo_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - momo_network

  fastapi:
    image: ganghyoun/moggulmoggul-ai:latest
    container_name: momo_fastapi
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - momo_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  celery:
    image: ganghyoun/moggulmoggul-ai:latest 
    container_name: momo_celery
    restart: unless-stopped
    # command를 FastAPI가 사용하는 celery_app을 가리키도록 수정
    command: celery -A app.celery_config.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - momo_network
    healthcheck:
      test: ["CMD", "celery", "-A", "app.celery_config.celery_app", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  momo_network:
    driver: bridge