# AI/docker-compose.yml

# version을 명시하여 호환성을 높입니다.
version: '3.8'

services:
  # FastAPI 애플리케이션 서버
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: momo_fastapi
    restart: always
    ports:
      - "8000:8000"
    # 이제 depends_on이 필요 없습니다. 외부 AWS 서비스에 접속합니다.
    # environment 변수는 .env 파일에서 주입되므로 여기서 제거합니다.
    env_file:
      - .env
    volumes:
      - .:/app

  # Celery 워커 서버
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: momo_celery
    restart: always
    command: celery -A app.celery_config.celery_app worker --loglevel=info
    # depends_on도 마찬가지로 필요 없습니다.
    env_file:
      - .env
    volumes:
      - .:/app

# postgres, redis, elasticsearch, kibana 서비스는 모두 제거합니다.