# AI/docker-compose.yml

# version을 명시하여 호환성을 높입니다.
version: '3.8'

services:
  # FastAPI 애플리케이션 서버
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: momo_fastapi
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

  # Celery 워커 서버
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: momo_celery
    restart: always
    command: celery -A app.celery_config.celery_app worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
